### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by moreamazingnick** [william-sy/icinga2-adaptive-teams-notification#1]
Could you please specify a license for your work.
The original work is [Apache-2.0 license](https://github.com/nisabek/icinga2-slack-notifications/blob/master/LICENSE)
and the adaption is [Apache-2.0 license](https://github.com/seffparker/icinga2-teams-notification/blob/main/LICENSE)

https://github.com/nisabek/icinga2-slack-notifications
https://github.com/seffparker/icinga2-teams-notification
Best Regards
Nicolas

**Comment by william-sy** [comment]
Licence added, Enjoy!
